language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - master
    - develop
bundler_args: --without development --path vendor/bundle
before_script:
  - psql -c 'create database mayushee_test;' -U postgres
script: "bundle exec rake db:migrate spec"
